name: Android Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/[email protected]
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      
      # Debug APK build
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      
      # Release APK build
      - name: Build Release APK
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          echo $RELEASE_KEYSTORE_PASSWORD > keystore.jks
          echo $RELEASE_KEYSTORE_ALIAS > keystore.properties
          echo $RELEASE_KEY_PASSWORD > keystore_password.txt
          ./gradlew assembleRelease --stacktrace
          
          # Clean up sensitive files
          rm keystore.jks keystore.properties keystore_password.txt
      
      # Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
          
